env:
  es6: true
  browser: true

parserOptions:
  ecmaVersion: 9
  sourceType: 'module'
  allowImportExportEverywhere: false

extends: ['eslint:recommended']

rules:
  max-len: 2
  no-console: 0
  block-spacing: 2
  space-infix-ops: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: 2
  semi: [2, 'never']
  indent: [2, 2, {'ignoreComments': true}]
  quotes: [2, 'single']
  one-var: [2, 'never']
  dot-location: [2, 'property']
  comma-dangle: [2, 'always-multiline']
  operator-linebreak: [2, 'before']
  space-before-blocks: [2, 'always']
  object-curly-spacing: [2, 'always']
  array-bracket-spacing: [2, 'never']
  no-multiple-empty-lines: [2, { 'max': 1, 'maxEOF': 0, 'maxBOF': 0 }]
